#Requires -Version 5.1
<#
.SYNOPSIS
  Parameterize mode-A hostPath for trace-mcp (one workspace → one instance).

.DESCRIPTION
  Derives Rancher node path from a Windows workspace path (no trial-and-error),
  writes deploy/local/patches/hostpath.yaml (primary) or an overlay under
  deploy/local/overlays/<slug>/ (secondary), or deploy/local/instances/<name>/
  when -Instance is set (isolated unified codebase stack), registers secondary
  into the docker/mcp-gateway catalog, then optionally kubectl apply -k.

  Formula SSOT: skill rancher-k3s-local → references/host-mount-windows.md
#>
[CmdletBinding()]
param(
  [Parameter(Mandatory = $false)]
  [string] $WorkspacePath = "",

  [string] $WorkspaceSlug = "",

  [string] $Namespace = "project-localdepot-dev",

  # Isolated full stack under deploy/local/instances/<name>/ (e.g. mcpverify).
  # Does not write deploy/local/patches/hostpath.yaml (localdepot primary stays untouched).
  [string] $Instance = "",

  # Local port-forward hint for -Instance (mcpverify default 18081).
  [int] $LocalPort = 0,

  # Secondary instance: self-contained overlay named trace-mcp-<slug>
  [switch] $Secondary,

  # Remove secondary registration (+ overlay) and rebuild gateway catalog
  [switch] $Unregister,

  # Only rebuild gateway ConfigMap / --servers from gateway/secondaries/
  [switch] $SyncCatalog,

  [switch] $WritePatchOnly,

  [switch] $SkipApply
)

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

function ConvertTo-RancherNodePath([string]$WindowsPath) {
  $full = [System.IO.Path]::GetFullPath($WindowsPath)
  if ($full -notmatch '^[A-Za-z]:\\') {
    throw "Not a Windows drive path: $WindowsPath"
  }
  $drive = $full.Substring(0, 1).ToLowerInvariant()
  $rest = $full.Substring(2).Replace('\', '/')
  return "/mnt/$drive$rest"
}

function ConvertTo-K8sSlug([string]$Name) {
  $s = $Name.ToLowerInvariant() -replace '[^a-z0-9-]', '-'
  $s = $s -replace '-+', '-'
  $s = $s.Trim('-')
  if ([string]::IsNullOrWhiteSpace($s)) { throw "WorkspaceSlug empty after sanitize" }
  if ($s.Length -gt 40) { $s = $s.Substring(0, 40).TrimEnd('-') }
  return $s
}

function Write-Utf8NoBom([string]$Path, [string]$Content) {
  $utf8 = New-Object System.Text.UTF8Encoding($false)
  [System.IO.File]::WriteAllText($Path, $Content, $utf8)
}

function Get-ToolAllowlistLines {
  return @(
    "search",
    "get_outline",
    "get_symbol",
    "find_usages",
    "get_change_impact",
    "get_task_context",
    "get_call_graph",
    "get_project_map",
    "load_tools",
    "get_preset_info"
  )
}

function Get-SecondarySlugs([string]$DeployLocal) {
  $dir = Join-Path $DeployLocal "gateway\secondaries"
  if (-not (Test-Path $dir)) { return @() }
  return @(Get-ChildItem -Path $dir -Filter "*.yaml" | Sort-Object Name | ForEach-Object { $_.BaseName })
}

function Sync-GatewayCatalog {
  param(
    [string] $DeployLocal,
    [string] $Namespace
  )

  $slugs = @(Get-SecondarySlugs $DeployLocal)
  $tools = Get-ToolAllowlistLines
  $serverNames = @("trace-mcp") + @($slugs | ForEach-Object { "trace-mcp-$_" })
  $serversCsv = ($serverNames -join ",")

  $catalogBody = @"
registry:
  trace-mcp:
    name: trace-mcp
    title: trace-mcp
    description: Framework-aware code graph MCP (verification backend).
    type: remote
    remote:
      transport_type: streamable-http
      url: http://trace-mcp.$Namespace.svc.cluster.local:3741/mcp?project=/workspaces/project
"@

  foreach ($s in $slugs) {
    $serverKey = "trace-mcp-$s"
    $catalogBody += @"

  ${serverKey}:
    name: ${serverKey}
    title: trace-mcp ($s)
    description: trace-mcp secondary workspace ($s).
    type: remote
    remote:
      transport_type: streamable-http
      url: http://${serverKey}.$Namespace.svc.cluster.local:3741/mcp?project=/workspaces/project
"@
  }

  $toolsBody = ""
  foreach ($name in $serverNames) {
    $toolsBody += "${name}:`n"
    foreach ($t in $tools) {
      $toolsBody += "  - $t`n"
    }
  }

  # Indent multiline ConfigMap data values by 4 spaces
  $catalogIndented = (($catalogBody -split "`n" | ForEach-Object { "    $_" }) -join "`n")
  $toolsIndented = (($toolsBody -split "`n" | ForEach-Object { "    $_" }) -join "`n").TrimEnd() + "`n"

  $configMap = @"
# Regenerated by apply-workspace.ps1 Sync-GatewayCatalog. Do not hand-edit.
# Secondaries: deploy/local/gateway/secondaries/<slug>.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: docker-mcp-gateway-config
  namespace: $Namespace
  labels:
    app.kubernetes.io/name: docker-mcp-gateway
    app.kubernetes.io/part-of: localdepot
data:
  catalog-localdepot.yaml: |
$catalogIndented
  tools.yaml: |
$toolsIndented
"@

  $gatewayDir = Join-Path $DeployLocal "gateway"
  New-Item -ItemType Directory -Force -Path $gatewayDir | Out-Null
  Write-Utf8NoBom (Join-Path $gatewayDir "configmap.yaml") $configMap

  $argsLines = @(
    "            - --catalog=/root/.docker/mcp/catalogs/localdepot.yaml",
    "            - --servers=$serversCsv",
    "            - --tools-config=/root/.docker/mcp/tools.yaml",
    "            - --transport=streaming",
    "            - --port=8080",
    "            - --host=0.0.0.0",
    "            - --allow-unauthenticated",
    "            - --verify-signatures=false",
    "            - --verbose"
  ) -join "`n"

  $serversPatch = @"
# Regenerated by apply-workspace.ps1 Sync-GatewayCatalog (--servers=$serversCsv).
apiVersion: apps/v1
kind: Deployment
metadata:
  name: docker-mcp-gateway
  namespace: $Namespace
spec:
  template:
    spec:
      containers:
        - name: gateway
          args:
$argsLines
"@

  $patchesDir = Join-Path $DeployLocal "patches"
  New-Item -ItemType Directory -Force -Path $patchesDir | Out-Null
  Write-Utf8NoBom (Join-Path $patchesDir "gateway-servers.yaml") $serversPatch

  # Keep docker-mcp-gateway/ mirror in sync for humans reading the folder
  Write-Utf8NoBom (Join-Path $DeployLocal "docker-mcp-gateway\catalog-localdepot.yaml") ($catalogBody.TrimEnd() + "`n")
  Write-Utf8NoBom (Join-Path $DeployLocal "docker-mcp-gateway\tools.yaml") ($toolsBody.TrimEnd() + "`n")

  Write-Host "Synced gateway catalog. servers=$serversCsv"
  if (@($slugs).Count -gt 0) {
    Write-Host ("  secondaries: " + ($slugs -join ", "))
  }
  else {
    Write-Host "  secondaries: (none)"
  }
}

function Register-Secondary([string]$DeployLocal, [string]$Slug, [string]$HostPath, [string]$Namespace) {
  $dir = Join-Path $DeployLocal "gateway\secondaries"
  New-Item -ItemType Directory -Force -Path $dir | Out-Null
  $meta = @"
# Registered by apply-workspace.ps1 -Secondary. Used by Sync-GatewayCatalog.
slug: $Slug
service: trace-mcp-$Slug
namespace: $Namespace
hostPath: $HostPath
"@
  Write-Utf8NoBom (Join-Path $dir "$Slug.yaml") $meta
  Write-Host "Registered secondary: gateway/secondaries/$Slug.yaml"
}

function Unregister-Secondary([string]$DeployLocal, [string]$Slug) {
  $meta = Join-Path $DeployLocal "gateway\secondaries\$Slug.yaml"
  $overlay = Join-Path $DeployLocal "overlays\$Slug"
  if (Test-Path $meta) {
    Remove-Item -Force $meta
    Write-Host "Removed registration: $meta"
  }
  else {
    Write-Host "No registration file for slug=$Slug"
  }
  if (Test-Path $overlay) {
    Remove-Item -Recurse -Force $overlay
    Write-Host "Removed overlay: $overlay"
  }
}

$repoRoot = Resolve-Path (Join-Path $PSScriptRoot "..\..")
$deployLocal = Join-Path $repoRoot "deploy\local"
$ctx = "rancher-desktop"

# --- Instance mode (unified codebase remote; isolated from localdepot primary) ---
if ($Instance) {
  if ($Secondary -or $Unregister -or $SyncCatalog) {
    throw "-Instance cannot be combined with -Secondary / -Unregister / -SyncCatalog."
  }
  $instanceName = ConvertTo-K8sSlug $Instance
  $instanceDir = Join-Path $deployLocal "instances\$instanceName"
  if (-not (Test-Path (Join-Path $instanceDir "kustomization.yaml"))) {
    throw "Instance not found: $instanceDir (missing kustomization.yaml)"
  }
  if (-not $WorkspacePath) {
    throw "-Instance requires -WorkspacePath (parent workspace root to mount)."
  }
  if ($Namespace -eq "project-localdepot-dev") {
    $Namespace = "project-$instanceName-dev"
  }
  if ($LocalPort -le 0) {
    $LocalPort = if ($instanceName -eq "mcpverify") { 18082 } else { 18080 }
  }

  $hostPath = ConvertTo-RancherNodePath $WorkspacePath
  Write-Host "Instance:  $instanceName"
  Write-Host "Namespace: $Namespace"
  Write-Host "Windows:   $([System.IO.Path]::GetFullPath($WorkspacePath))"
  Write-Host "hostPath:  $hostPath"
  Write-Host "LocalPort: $LocalPort"

  $patchDir = Join-Path $instanceDir "patches"
  New-Item -ItemType Directory -Force -Path $patchDir | Out-Null
  $patch = @"
# Instance patch only. Generated by apply-workspace.ps1 -Instance $instanceName.
# Formula: rancher-k3s-local -> references/host-mount-windows.md (C:\... -> /mnt/c/...)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: trace-mcp
  namespace: $Namespace
spec:
  template:
    spec:
      volumes:
        - name: workspace
          hostPath:
            path: $hostPath
            type: Directory
"@
  Write-Utf8NoBom (Join-Path $patchDir "hostpath.yaml") $patch

  $tools = Get-ToolAllowlistLines
  $toolsBody = "trace-mcp:`n"
  foreach ($t in $tools) { $toolsBody += "  - $t`n" }
  $catalogBody = @"
registry:
  trace-mcp:
    name: trace-mcp
    title: trace-mcp
    description: Unified codebase remote (all repos under mounted workspace root).
    type: remote
    remote:
      transport_type: streamable-http
      url: http://trace-mcp.$Namespace.svc.cluster.local:3741/mcp
"@
  $catalogIndented = (($catalogBody -split "`n" | ForEach-Object { "    $_" }) -join "`n")
  $toolsIndented = (($toolsBody -split "`n" | ForEach-Object { "    $_" }) -join "`n").TrimEnd() + "`n"
  $configMap = @"
# Regenerated by apply-workspace.ps1 -Instance $instanceName. Single unified remote.
# No ?project= on catalog URL: multi-repo mounts hang on parent path; clients scope via mcp.json projects.
apiVersion: v1
kind: ConfigMap
metadata:
  name: docker-mcp-gateway-config
  namespace: $Namespace
  labels:
    app.kubernetes.io/name: docker-mcp-gateway
    app.kubernetes.io/part-of: $instanceName
data:
  catalog-localdepot.yaml: |
$catalogIndented
  tools.yaml: |
$toolsIndented
"@
  $gwDir = Join-Path $instanceDir "gateway"
  New-Item -ItemType Directory -Force -Path $gwDir | Out-Null
  Write-Utf8NoBom (Join-Path $gwDir "configmap.yaml") $configMap

  if ($WritePatchOnly -or $SkipApply) {
    Write-Host "Skip apply (-WritePatchOnly / -SkipApply)."
    exit 0
  }

  Write-Host "kubectl --context $ctx apply -k `"$instanceDir`""
  kubectl --context $ctx apply -k $instanceDir
  if ($LASTEXITCODE -ne 0) { throw "kubectl apply failed ($LASTEXITCODE) for $instanceDir" }

  Write-Host "Waiting for deploy/trace-mcp ..."
  kubectl --context $ctx -n $Namespace rollout status deploy/trace-mcp --timeout=300s
  if ($LASTEXITCODE -ne 0) { throw "trace-mcp rollout failed ($LASTEXITCODE)" }
  Write-Host "Waiting for deploy/docker-mcp-gateway ..."
  kubectl --context $ctx -n $Namespace rollout status deploy/docker-mcp-gateway --timeout=180s
  if ($LASTEXITCODE -ne 0) { throw "gateway rollout failed ($LASTEXITCODE)" }

  Write-Host "Mount probe (once):"
  kubectl --context $ctx -n $Namespace exec deploy/trace-mcp -- ls /workspaces/project
  if ($LASTEXITCODE -ne 0) {
    Write-Warning "Mount probe failed. Do NOT trial alternate path spellings. Stop mode A → product mode B. See host-mount-windows.md."
    exit 2
  }

  Write-Host "Restarting docker-mcp-gateway so it rediscovers tools after trace is ready..."
  kubectl --context $ctx -n $Namespace rollout restart deploy/docker-mcp-gateway
  kubectl --context $ctx -n $Namespace rollout status deploy/docker-mcp-gateway --timeout=180s
  if ($LASTEXITCODE -ne 0) { throw "gateway restart failed ($LASTEXITCODE)" }

  Write-Host "OK. Gateway: kubectl --context $ctx -n $Namespace port-forward --address 127.0.0.1 svc/docker-mcp-gateway ${LocalPort}:8080"
  Write-Host "Client URL: http://127.0.0.1:${LocalPort}/mcp  (same url for all repos; scope via mcp.json projects)"
  exit 0
}

if ($SyncCatalog -and -not $Secondary -and -not $Unregister -and -not $WorkspacePath) {
  Sync-GatewayCatalog -DeployLocal $deployLocal -Namespace $Namespace
  if ($WritePatchOnly -or $SkipApply) {
    Write-Host "Skip apply (-WritePatchOnly / -SkipApply)."
    exit 0
  }
  Write-Host "kubectl --context $ctx apply -k `"$deployLocal`""
  kubectl --context $ctx apply -k $deployLocal
  if ($LASTEXITCODE -ne 0) { throw "kubectl apply failed ($LASTEXITCODE)" }
  Write-Host "Restarting docker-mcp-gateway to reload catalog..."
  kubectl --context $ctx -n $Namespace rollout restart deploy/docker-mcp-gateway
  kubectl --context $ctx -n $Namespace rollout status deploy/docker-mcp-gateway --timeout=180s
  if ($LASTEXITCODE -ne 0) { throw "gateway rollout failed ($LASTEXITCODE)" }
  Write-Host "OK (catalog synced)."
  exit 0
}

if (-not $WorkspacePath -and -not $Unregister) {
  throw "WorkspacePath is required unless -SyncCatalog or -Unregister (with -WorkspaceSlug)."
}

if ($Unregister) {
  if (-not $WorkspaceSlug -and $WorkspacePath) {
    $WorkspaceSlug = Split-Path -Leaf ([System.IO.Path]::GetFullPath($WorkspacePath))
  }
  if (-not $WorkspaceSlug) { throw "Unregister requires -WorkspaceSlug (or -WorkspacePath to derive slug)." }
  $slug = ConvertTo-K8sSlug $WorkspaceSlug
  Write-Host "Unregister secondary slug=$slug"
  Unregister-Secondary -DeployLocal $deployLocal -Slug $slug
  Sync-GatewayCatalog -DeployLocal $deployLocal -Namespace $Namespace
  if ($WritePatchOnly -or $SkipApply) {
    Write-Host "Skip apply (-WritePatchOnly / -SkipApply)."
    exit 0
  }
  Write-Host "kubectl --context $ctx apply -k `"$deployLocal`""
  kubectl --context $ctx apply -k $deployLocal
  if ($LASTEXITCODE -ne 0) { throw "kubectl apply failed ($LASTEXITCODE)" }
  $deployName = "trace-mcp-$slug"
  kubectl --context $ctx -n $Namespace delete deploy,svc -l "app.kubernetes.io/name=$deployName" --ignore-not-found | Out-Host
  kubectl --context $ctx -n $Namespace delete deploy/$deployName svc/$deployName --ignore-not-found | Out-Host
  kubectl --context $ctx -n $Namespace rollout restart deploy/docker-mcp-gateway
  kubectl --context $ctx -n $Namespace rollout status deploy/docker-mcp-gateway --timeout=180s
  Write-Host "OK (unregistered $slug)."
  exit 0
}

$hostPath = ConvertTo-RancherNodePath $WorkspacePath

if (-not $WorkspaceSlug) {
  $WorkspaceSlug = Split-Path -Leaf ([System.IO.Path]::GetFullPath($WorkspacePath))
}
$slug = ConvertTo-K8sSlug $WorkspaceSlug

Write-Host "Windows:  $([System.IO.Path]::GetFullPath($WorkspacePath))"
Write-Host "hostPath: $hostPath"
Write-Host "slug:     $slug"
Write-Host "mode:     $(if ($Secondary) { 'secondary (overlay + catalog)' } else { 'primary (patches/hostpath.yaml)' })"

$applyTargets = @()

if ($Secondary) {
  $overlayDir = Join-Path $deployLocal "overlays\$slug"
  New-Item -ItemType Directory -Force -Path $overlayDir | Out-Null
  $deployName = "trace-mcp-$slug"

  $resources = @"
# Generated by apply-workspace.ps1 (secondary). Catalog updated via gateway/secondaries/.
apiVersion: apps/v1
kind: Deployment
metadata:
  name: $deployName
  namespace: $Namespace
  labels:
    app.kubernetes.io/name: $deployName
    app.kubernetes.io/part-of: localdepot
    app.kubernetes.io/component: mcp-backend
    localdepot/workspace-slug: $slug
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: $deployName
  template:
    metadata:
      labels:
        app.kubernetes.io/name: $deployName
        app.kubernetes.io/part-of: localdepot
        app.kubernetes.io/component: mcp-backend
        localdepot/workspace-slug: $slug
    spec:
      containers:
        - name: trace-mcp
          image: localdepot/trace-mcp:3.31.3
          imagePullPolicy: IfNotPresent
          env:
            - name: TRACE_PROJECT_ROOT
              value: /workspaces/project
            - name: TRACE_HOME
              value: /workspaces/project/.cache/trace-home
            - name: TRACE_MCP_TELEMETRY
              value: "off"
          ports:
            - name: mcp
              containerPort: 3741
          readinessProbe:
            tcpSocket:
              port: mcp
            initialDelaySeconds: 15
            periodSeconds: 10
            failureThreshold: 30
          livenessProbe:
            tcpSocket:
              port: mcp
            initialDelaySeconds: 60
            periodSeconds: 30
          resources:
            requests:
              cpu: 200m
              memory: 512Mi
            limits:
              cpu: "2"
              memory: 3Gi
          volumeMounts:
            - name: workspace
              mountPath: /workspaces/project
      volumes:
        - name: workspace
          hostPath:
            path: $hostPath
            type: Directory
---
apiVersion: v1
kind: Service
metadata:
  name: $deployName
  namespace: $Namespace
  labels:
    app.kubernetes.io/name: $deployName
    app.kubernetes.io/part-of: localdepot
    localdepot/workspace-slug: $slug
spec:
  selector:
    app.kubernetes.io/name: $deployName
  ports:
    - name: mcp
      port: 3741
      targetPort: 3741
"@

  $kustomization = @"
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: $Namespace
resources:
  - trace-mcp.yaml
"@

  Write-Utf8NoBom (Join-Path $overlayDir "trace-mcp.yaml") $resources
  Write-Utf8NoBom (Join-Path $overlayDir "kustomization.yaml") $kustomization
  Register-Secondary -DeployLocal $deployLocal -Slug $slug -HostPath $hostPath -Namespace $Namespace
  Sync-GatewayCatalog -DeployLocal $deployLocal -Namespace $Namespace
  $applyTargets += $overlayDir
  $applyTargets += $deployLocal
  Write-Host "Wrote overlay: $overlayDir"
  Write-Host "Service DNS: ${deployName}.${Namespace}.svc.cluster.local:3741"
}
else {
  $patchPath = Join-Path $deployLocal "patches\hostpath.yaml"
  $patchDir = Split-Path $patchPath -Parent
  New-Item -ItemType Directory -Force -Path $patchDir | Out-Null

  $patch = @"
# Instance patch only. Generated by apply-workspace.ps1 - not a global truth.
# Formula: rancher-k3s-local -> references/host-mount-windows.md (C:\... -> /mnt/c/...)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: trace-mcp
  namespace: $Namespace
spec:
  template:
    spec:
      volumes:
        - name: workspace
          hostPath:
            path: $hostPath
            type: Directory
"@
  Write-Utf8NoBom $patchPath $patch
  # Keep catalog consistent with any existing secondaries
  Sync-GatewayCatalog -DeployLocal $deployLocal -Namespace $Namespace
  $applyTargets += $deployLocal
  Write-Host "Wrote patch: $patchPath"
}

if ($WritePatchOnly -or $SkipApply) {
  Write-Host "Skip apply (-WritePatchOnly / -SkipApply)."
  exit 0
}

foreach ($target in $applyTargets) {
  Write-Host "kubectl --context $ctx apply -k `"$target`""
  kubectl --context $ctx apply -k $target
  if ($LASTEXITCODE -ne 0) { throw "kubectl apply failed ($LASTEXITCODE) for $target" }
}

$deployName = if ($Secondary) { "trace-mcp-$slug" } else { "trace-mcp" }
Write-Host "Waiting for deploy/$deployName ..."
kubectl --context $ctx -n $Namespace rollout status "deploy/$deployName" --timeout=300s
if ($LASTEXITCODE -ne 0) { throw "rollout status failed ($LASTEXITCODE)" }

Write-Host "Mount probe (once):"
kubectl --context $ctx -n $Namespace exec "deploy/$deployName" -- ls /workspaces/project
if ($LASTEXITCODE -ne 0) {
  Write-Warning "Mount probe failed. Do NOT trial alternate path spellings. Stop mode A → product mode B. See host-mount-windows.md."
  exit 2
}

if ($Secondary) {
  Write-Host "Restarting docker-mcp-gateway to reload catalog..."
  kubectl --context $ctx -n $Namespace rollout restart deploy/docker-mcp-gateway
  kubectl --context $ctx -n $Namespace rollout status deploy/docker-mcp-gateway --timeout=180s
  if ($LASTEXITCODE -ne 0) { throw "gateway rollout failed ($LASTEXITCODE)" }
}

Write-Host "OK. Gateway: kubectl --context $ctx -n $Namespace port-forward --address 127.0.0.1 svc/docker-mcp-gateway 18080:8080"
